<?php
    include 'header.php';
?>
<div class="glossaryContainer">
    <h1>Glossary</h1>
    <div class="economy">
        <img src="./images/economy.webp" alt="">
        <div class="economyContent">
            <h1>Economy</h1>
            <p>Automatic stabilisers are a form of fiscal policy structured to counter fluctuations in the economic growth of a nation through its normal operation without additional, appropriate government or policymaker's authorisation. Gross domestic product (GDP) is a monetary indicator of the market value of all the final goods and services produced over a given period of time. You must have often heard the term “per capita income” or read it in the newspaper in the economic section. Business economics is an applied economics field that studies corporations' financial, organisational, market-related, and environmental issues.  </p><br>
        </div>
    </div>
    <div class="taxation">
        <div class="taxationContent">
            <h1>Taxation</h1>
            <p>Taxation means the imposition of compulsory levies on individuals or entities by the government. Cess is a form of tax and an additional levy by the Central Government to raise funds for specific purposes. Input tax credit refers to the mechanism of claiming a reduction of tax paid on the inputs of a business or profession.  Every law requires that the registered person file the return in a certain format and within the period specified in the specific law. </p><br>
        </div>
            <img src="./images/taxation.webp" alt="">
    </div>
    <div class="financeAccounting">
        <img src="./images/financeAccounting.webp" alt="">
        <div class="financeAccountingContent">
            <h1>Corporate Finance and Accounting</h1>
            <p>Financial analysis is the method of reviewing companies, programs, expenditures, and other activities relevant to finance to assess their performance and appropriateness. Operating revenue refers to the revenue generated by a company from its primary activities. A debit note is a document a seller uses to remind the purchaser of current debt obligations, or a document produced by a purchaser when returning goods purchased on loan.</p><br>
        </div>
    </div>
    <div class="business">
        <div class="businessContent">
            <h1>Business</h1>
            <p>Strategic alliance refers to an agreement or arrangement between two or more parties to carry out projects for their common benefit. Employees' State Insurance Corporation (ESIC) is a government organisation that manages the Employees' State Insurance (ESI) scheme. Price discrimination is a microeconomic pricing technique, in which the same supplier transacts equivalent or substantially equivalent goods or services in separate countries at varying prices. A customer refers to a business or an individual who purchases the goods or services of another company.</p> <br>
        </div>
        <img src="./images/business.webp" alt="">
    </div>
    <div class="trading">
        <img src="./images/trading.webp" alt="">
        <div class="tradingContent">
            <h1>Trading</h1>
            <p>S&P/TSX Composite Index is a Canadian Index, which tracks the performance of listed companies on the Toronto Stock Exchange (TSX).  Squaring off is a trading style that day trade investors use to make profit from the market volatility.  Relative strength is a calculation of the price trend of a stock or a financial instrument in comparison to another instrument, stock, or industry.  A prop-shop is a trading company that deploys its own resources to generate profits from trading.  </p><br>
        </div>
    </div>
</div>
<footer>
    <?php
        include 'footer.php';
    ?>
</footer>